apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: nginx-1
  name: nginx-1
  namespace: site
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:
      - image: alexheld/site
        imagePullPolicy: Always
        name: site-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx-2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2020-07-06T00:05:58Z"
    lastUpdateTime: "2020-07-06T00:05:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-07-06T00:05:39Z"
    lastUpdateTime: "2020-07-06T00:05:58Z"
    message: ReplicaSet "nginx-1-74c578f86" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
