---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "site"
  namespace: "site"
  labels:
    app: "nginx-1"
spec:
  ports:
  - name: "80-to-8080-tcp"
    protocol: "TCP"
    port: 80
    targetPort: 80
  - name: "443-to-443-tcp"
    protocol: "TCP"
    port: 443
    targetPort: 443
  selector:
    app: "nginx-1"
  type: "LoadBalancer"
  loadBalancerIP: ""
